#!/bin/bash


# ${1,,} : 将字符串转换为小写
if [ "${1,,}" == 'install' ]; then
   #安装
   source _Scripts/Install/Install  "`pwd`"
   exit 0
elif [ "${1,,}" == 'patch' ]; then
   #补丁
   source _Scripts/Patchs/Patch  "`pwd`/"
   exit 0
elif [ "${1,,}" == 'init' ]; then
    #初始化
    #         $1:   工作根目录                
    #       [$2]:   语言(en|cn<默认>)           
    #       [$3]:   主题(next<默认>|)           
    #       [$4]:   作者
    source _Scripts/Init/Init  "`pwd`/" "${2}" "${3}"  "${4}"
   exit 0
else 
   echo 
   echo "Start: Parameter cannot be empty"
   echo "Start: 参数不能为空"
   echo 
   exit 1
fi
